### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hamilbrian**
I threw this together. We might have an easier time working with this in html. It doesn't work yet either, but it's a start. Don't actually merge it with anything though. Just sent this as a reference.

### CODE REVIEW

**Comment by larryalogan** [comment]
ok

**Comment by whs-codervets** [comment]
Thanks.

**Review by geo8103 — COMMENTED** [review]
ok, but can you explain if this will work. thanks

**Comment by hamilbrian** [comment]
It doesn't work at the moment, but it should be much easier to call the api
without going through all the react components and we will at least have a
working web version. I was really tired but I felt compelled to at least
get it started. An api call in html I think will be easier to figure out
for a web page since it's been done about a billion times.

**Pull request merged**
